name: Workflow2_feature_trunk

on:
  pull_request:
    branches:
      - trunk
    types: [ opened ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'


      - name: Integration test
        run: mvn -Dtest=es.codeurjc.ais.nitflex.integration.UrlUtilsIntegrationTest test

      - name: Unitary test
        run: mvn -Dtest=es.codeurjc.ais.nitflex.unitary.FilmServiceUnitaryTest test

      - name: E2E test
        run: mvn -Dtest=es.codeurjc.ais.nitflex.e2e.selenium.FilmUITest -Dbrowser=chrome test