name: Workflow4_CronTrunk

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, firefox, edge, safari]
        exclude:
          - os: ubuntu-latest
            browser: edge
          - os: ubuntu-latest
            browser: safari
          - os: windows-latest
            browser: safari
          - os: macos-latest
            browser: edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run E2E Test
        run: mvn  -Dtest="es.codeurjc.ais.nitflex.e2e.selenium.FilmUITest" -Dbrowser=${{ matrix.browser }} test

  upload_image:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '17'

        - name: 'Checkout'
          uses: actions/checkout@v4

        - name: 'Generate tag'
          run: echo "tag=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
          id: timestamp

        - name: 'Generate Docker image'
          run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ env.tag }}

        - name: 'Login to DockerHub'
          run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

        - name: 'Push image to DockerHub'
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ env.tag }}



