name: Workflow3_Docker_Azure

on:
  create:
    branches:
      - release/**
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: 'Generate Tag'
        run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_OUTPUT
        id: project

      - name: 'Generate Docker image'
        run: |
          mvn spring-boot:build-image -DskipTests
                -Dspring-boot.build-image.imageName=
                      ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ steps.project.outputs.tag }}

      - name: 'Login to DockerHub'
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: 'Push image to DockerHub'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ steps.project.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deoploy to Azure Container'
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_GROUP }} \
            --name nitflex \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ steps.project.outputs.tag }} \
            --dns-name-label nitflex-jljlo \
            --ports 8080
  test:
    runs-on: ubuntu-latest
    name: 'Run Smoke Test'
    needs: deploy
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Run Smoke Test'
        run: mvn -Dhost="http://nitflex-jljlo.westeurope.azurecontainer.io:8080/" test -Dtest=SmokeTest